name: Invite user(s) to slack
on:
  push:
    branches:
      - "master"

  workflow_dispatch:
    inputs:
      channels:
        type: string
        description: Which channels to be added
        required: true
        default: 'infosec,tooprivate'
      emails:
        type: string
        description: Which user email
        required: true
        default: 'luis@sanmartin.dev'

jobs:
  inviteUsers:
    name: Adding users to slack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download slack-inviter
      run: |
        curl -LO https://github.com/pathcl/slack-inviter/releases/download/v0.2/slack-inviter_0.2_Linux_x86_64.tar.gz
        tar xfvz slack-inviter_0.2_Linux_x86_64.tar.gz
        chmod a+x slack-inviter

    - name: Set defaults if no inputs (push to master event)
      if: github.event.inputs.channels == ''
      run: |
        ./slack-inviter -channels infosec,tooprivate -debug -emails luis@sanmartin.dev -private -action add


    - name: Add user(s) to private channels
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      run: |
        ./slack-inviter -channels "${{ github.event.inputs.channels }}" -debug -emails "${{ github.event.inputs.emails }}" -private -action add
