name: Invite user(s) to slack
on:
  push:
    branches:
      - "master"

  workflow_dispatch:
    inputs:
      channels:
        type: string
        description: Which channels to be added
        required: true
      emails:
        type: string
        description: Which user email
        required: true

jobs:
  inviteUsers:
    name: Adding users to slack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download slack-inviter
      run: |
        curl -LO https://github.com/pathcl/slack-inviter/releases/download/v0.1/slack-inviter_0.1_Linux_x86_64.tar.gz
        tar xfvz slack-inviter_0.1_Linux_x86_64.tar.gz
        chmod a+x slack-inviter


    - name: Add user(s) to private channels
      run: |
        echo ./slack-inviter -channels "${{ github.event.inputs.channels }}" -debug -emails "${{ github.event.inputs.emails }}" -private -action add -api_token my-token
